/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CargaRouteImport } from './routes/carga'
import { Route as DemoRouteImport } from './routes/demo'
import { Route as ModoDemoRouteImport } from './routes/modo-demo'
import { Route as FamiliaIdRouteImport } from './routes/familia.$id'
import { Route as PacienteIdRouteImport } from './routes/paciente.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CargaRoute = CargaRouteImport.update({
  id: '/carga',
  path: '/carga',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoRoute = DemoRouteImport.update({
  id: '/demo',
  path: '/demo',
  getParentRoute: () => rootRouteImport,
} as any)
const ModoDemoRoute = ModoDemoRouteImport.update({
  id: '/modo-demo',
  path: '/modo-demo',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliaIdRoute = FamiliaIdRouteImport.update({
  id: '/familia/$id',
  path: '/familia/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PacienteIdRoute = PacienteIdRouteImport.update({
  id: '/paciente/$id',
  path: '/paciente/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/demo': typeof DemoRoute
  '/modo-demo': typeof ModoDemoRoute
  '/familia/$id': typeof FamiliaIdRoute
  '/paciente/$id': typeof PacienteIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/demo': typeof DemoRoute
  '/modo-demo': typeof ModoDemoRoute
  '/familia/$id': typeof FamiliaIdRoute
  '/paciente/$id': typeof PacienteIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/carga': typeof CargaRoute
  '/demo': typeof DemoRoute
  '/modo-demo': typeof ModoDemoRoute
  '/familia/$id': typeof FamiliaIdRoute
  '/paciente/$id': typeof PacienteIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/carga' | '/demo' | '/modo-demo' | '/familia/$id' | '/paciente/$id'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/carga' | '/demo' | '/modo-demo' | '/familia/$id' | '/paciente/$id'
  id:
    | '__root__'
    | '/'
    | '/carga'
    | '/demo'
    | '/modo-demo'
    | '/familia/$id'
    | '/paciente/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CargaRoute: typeof CargaRoute
  DemoRoute: typeof DemoRoute
  ModoDemoRoute: typeof ModoDemoRoute
  FamiliaIdRoute: typeof FamiliaIdRoute
  PacienteIdRoute: typeof PacienteIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carga': {
      id: '/carga'
      path: '/carga'
      fullPath: '/carga'
      preLoaderRoute: typeof CargaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo': {
      id: '/demo'
      path: '/demo'
      fullPath: '/demo'
      preLoaderRoute: typeof DemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/modo-demo': {
      id: '/modo-demo'
      path: '/modo-demo'
      fullPath: '/modo-demo'
      preLoaderRoute: typeof ModoDemoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familia/$id': {
      id: '/familia/$id'
      path: '/familia/$id'
      fullPath: '/familia/$id'
      preLoaderRoute: typeof FamiliaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/paciente/$id': {
      id: '/paciente/$id'
      path: '/paciente/$id'
      fullPath: '/paciente/$id'
      preLoaderRoute: typeof PacienteIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CargaRoute: CargaRoute,
  DemoRoute: DemoRoute,
  ModoDemoRoute: ModoDemoRoute,
  FamiliaIdRoute: FamiliaIdRoute,
  PacienteIdRoute: PacienteIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
